"""
Comprehensive AI Tools discovery adapter.

Uses multiple legitimate sources:
1. Curated seed list of well-known AI tools (verifiable, real data)
2. GitHub API search across multiple AI-related topics
3. Product Hunt API (if available)

Every record has a real, traceable source URL.
No fabricated data.
"""
import datetime
import logging
import asyncio
from typing import List, Dict, Optional
from ai_orbit.discovery.base import BaseAdapter
from ai_orbit.validation.schemas import ToolContent, EntityType, FullRecord, SourceProvenance

logger = logging.getLogger(__name__)

# ─── Curated seed list of REAL AI tools ───────────────────────────────────────
# Every entry here is a real, publicly verifiable AI product.
# source_url = where we know about it (official site or GitHub)
# We provide known metadata to avoid needing to scrape blocked sites.

CURATED_AI_TOOLS = [
    # ── Text / Writing / Content Generation ──
    {"name": "ChatGPT", "url": "https://openai.com/chatgpt", "company": "OpenAI", "description": "Conversational AI assistant powered by GPT models for text generation, coding assistance, analysis, and creative writing.", "primary_task": "Text Generation", "categories": ["Chatbot", "Writing", "Coding"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, images, files", "outputs": "Generated text, code, analysis, summaries"},
    {"name": "Claude", "url": "https://claude.ai", "company": "Anthropic", "description": "AI assistant built with Constitutional AI for helpful, harmless, and honest conversations, long-document analysis, and coding.", "primary_task": "Text Generation", "categories": ["Chatbot", "Writing", "Coding"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, documents, images", "outputs": "Generated text, code, analysis"},
    {"name": "Gemini", "url": "https://gemini.google.com", "company": "Google DeepMind", "description": "Multimodal AI assistant by Google capable of understanding text, images, audio, and video for conversation and content creation.", "primary_task": "Text Generation", "categories": ["Chatbot", "Multimodal"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text, images, audio, video", "outputs": "Generated text, images, code"},
    {"name": "Jasper", "url": "https://www.jasper.ai", "company": "Jasper AI", "description": "AI-powered marketing content platform for creating blog posts, social media content, ad copy, and brand-consistent marketing materials.", "primary_task": "Content Generation", "categories": ["Marketing", "Writing", "Copywriting"], "pricing": "PAID", "open_source": False, "inputs": "Marketing briefs, brand voice, prompts", "outputs": "Blog posts, ad copy, social media content"},
    {"name": "Copy.ai", "url": "https://www.copy.ai", "company": "Copy.ai", "description": "AI copywriting tool for generating marketing copy, email content, social media posts, and product descriptions.", "primary_task": "Copywriting", "categories": ["Marketing", "Writing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Product details, writing prompts", "outputs": "Marketing copy, emails, product descriptions"},
    {"name": "Writesonic", "url": "https://writesonic.com", "company": "Writesonic", "description": "AI writing and SEO tool for generating articles, blog posts, landing pages, and ad copy with built-in fact-checking.", "primary_task": "Content Generation", "categories": ["Writing", "SEO", "Marketing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Topic keywords, outlines, prompts", "outputs": "Articles, blog posts, landing pages"},
    {"name": "Rytr", "url": "https://rytr.me", "company": "Rytr", "description": "AI writing assistant for creating content across 40+ use cases including emails, blogs, social media, and website copy.", "primary_task": "Content Generation", "categories": ["Writing", "Marketing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Use case selection, keywords, tone", "outputs": "Blog posts, emails, social media content"},
    {"name": "Notion AI", "url": "https://www.notion.so/product/ai", "company": "Notion", "description": "AI assistant integrated into Notion workspace for writing, summarizing, brainstorming, editing, and translating within notes and documents.", "primary_task": "Productivity", "categories": ["Writing", "Productivity", "Knowledge Management"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Existing notes, documents, prompts", "outputs": "Summaries, drafts, action items, translations"},
    {"name": "Grammarly", "url": "https://www.grammarly.com", "company": "Grammarly", "description": "AI-powered writing assistant for grammar checking, tone detection, clarity improvement, and plagiarism detection across platforms.", "primary_task": "Writing Assistance", "categories": ["Writing", "Grammar", "Editing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Written text, documents, emails", "outputs": "Grammar corrections, tone suggestions, clarity improvements"},
    {"name": "QuillBot", "url": "https://quillbot.com", "company": "QuillBot", "description": "AI paraphrasing and grammar checking tool for rewriting text, summarizing content, and improving writing quality.", "primary_task": "Paraphrasing", "categories": ["Writing", "Paraphrasing", "Grammar"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text passages, documents", "outputs": "Paraphrased text, summaries, grammar fixes"},

    # ── Image Generation ──
    {"name": "Midjourney", "url": "https://www.midjourney.com", "company": "Midjourney Inc.", "description": "AI image generation tool that creates photorealistic and artistic images from text descriptions via Discord and web interface.", "primary_task": "Image Generation", "categories": ["Image Generation", "Art", "Design"], "pricing": "PAID", "open_source": False, "inputs": "Text prompts, image references", "outputs": "Generated images in multiple styles"},
    {"name": "DALL-E 3", "url": "https://openai.com/dall-e-3", "company": "OpenAI", "description": "Advanced text-to-image model by OpenAI that generates detailed, accurate images from natural language descriptions.", "primary_task": "Image Generation", "categories": ["Image Generation", "Art"], "pricing": "PAID", "open_source": False, "inputs": "Text prompts", "outputs": "Generated images"},
    {"name": "Stable Diffusion", "url": "https://stability.ai", "company": "Stability AI", "description": "Open-source text-to-image diffusion model enabling high-quality image generation, inpainting, and image-to-image translation.", "primary_task": "Image Generation", "categories": ["Image Generation", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Text prompts, seed images", "outputs": "Generated images, variations"},
    {"name": "Leonardo AI", "url": "https://leonardo.ai", "company": "Leonardo AI", "description": "AI-powered creative platform for generating production-quality visual assets, game art, and design elements.", "primary_task": "Image Generation", "categories": ["Image Generation", "Game Art", "Design"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, reference images", "outputs": "Game assets, concept art, textures"},
    {"name": "Canva AI", "url": "https://www.canva.com/ai-image-generator", "company": "Canva", "description": "AI image generator and design tools integrated into Canva's design platform for creating graphics, presentations, and visual content.", "primary_task": "Design", "categories": ["Design", "Image Generation", "Marketing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, design templates", "outputs": "Graphics, presentations, social media visuals"},
    {"name": "Adobe Firefly", "url": "https://www.adobe.com/products/firefly.html", "company": "Adobe", "description": "Generative AI model for creating images, text effects, and vector graphics, trained on licensed and public domain content.", "primary_task": "Image Generation", "categories": ["Image Generation", "Design", "Creative"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, reference images", "outputs": "Generated images, text effects, vectors"},
    {"name": "Ideogram", "url": "https://ideogram.ai", "company": "Ideogram", "description": "AI image generation platform specializing in accurate text rendering within generated images and photorealistic outputs.", "primary_task": "Image Generation", "categories": ["Image Generation", "Typography"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts with typography instructions", "outputs": "Generated images with accurate text"},
    {"name": "Playground AI", "url": "https://playground.com", "company": "Playground AI", "description": "Free AI image generation platform offering mixed image editing with multiple AI models and styles.", "primary_task": "Image Generation", "categories": ["Image Generation", "Editing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, uploaded images", "outputs": "Generated and edited images"},

    # ── Video Generation ──
    {"name": "Runway", "url": "https://runwayml.com", "company": "Runway", "description": "AI-powered creative suite for video generation, editing, and visual effects including Gen-2 text-to-video and motion brush tools.", "primary_task": "Video Generation", "categories": ["Video Generation", "Video Editing", "VFX"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, images, video clips", "outputs": "Generated videos, edited footage, VFX"},
    {"name": "Synthesia", "url": "https://www.synthesia.io", "company": "Synthesia", "description": "AI video generation platform that creates professional videos with AI avatars and voiceovers from text scripts.", "primary_task": "Video Generation", "categories": ["Video Generation", "Training Videos"], "pricing": "PAID", "open_source": False, "inputs": "Text scripts, avatar selection", "outputs": "AI-generated presenter videos"},
    {"name": "HeyGen", "url": "https://www.heygen.com", "company": "HeyGen", "description": "AI video creation platform for producing personalized avatar videos, translations, and video content at scale.", "primary_task": "Video Generation", "categories": ["Video Generation", "Avatars"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text scripts, avatar/voice selection", "outputs": "AI avatar videos, translated videos"},
    {"name": "Pika", "url": "https://pika.art", "company": "Pika Labs", "description": "AI video generation and editing tool that creates and modifies videos from text, images, and existing video clips.", "primary_task": "Video Generation", "categories": ["Video Generation", "Video Editing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, images, video clips", "outputs": "Generated short videos, video edits"},
    {"name": "Luma Dream Machine", "url": "https://lumalabs.ai/dream-machine", "company": "Luma AI", "description": "AI video generation model that creates realistic, high-quality videos from text and image inputs.", "primary_task": "Video Generation", "categories": ["Video Generation"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, reference images", "outputs": "Generated video clips"},
    {"name": "Descript", "url": "https://www.descript.com", "company": "Descript", "description": "AI-powered video and audio editing platform with text-based editing, transcription, screen recording, and AI voice cloning.", "primary_task": "Video Editing", "categories": ["Video Editing", "Audio Editing", "Transcription"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Video files, audio files, text edits", "outputs": "Edited videos, transcripts, podcasts"},

    # ── Audio / Music / Voice ──
    {"name": "ElevenLabs", "url": "https://elevenlabs.io", "company": "ElevenLabs", "description": "AI voice synthesis platform for generating natural-sounding speech, voice cloning, and audio dubbing in multiple languages.", "primary_task": "Voice Synthesis", "categories": ["Text-to-Speech", "Voice Cloning", "Audio"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text, voice samples for cloning", "outputs": "Synthesized speech audio, dubbed audio"},
    {"name": "Murf AI", "url": "https://murf.ai", "company": "Murf AI", "description": "AI text-to-speech platform offering realistic voiceovers for videos, presentations, and e-learning content.", "primary_task": "Text-to-Speech", "categories": ["Text-to-Speech", "Voiceover"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text scripts, voice selection", "outputs": "AI voiceover audio files"},
    {"name": "Suno", "url": "https://suno.com", "company": "Suno", "description": "AI music generation tool that creates complete songs with vocals, instruments, and lyrics from text prompts.", "primary_task": "Music Generation", "categories": ["Music Generation", "Audio"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, style descriptions, lyrics", "outputs": "Generated songs with vocals and instruments"},
    {"name": "Udio", "url": "https://www.udio.com", "company": "Udio", "description": "AI music generation platform for creating high-quality songs across genres with vocals and instrumentation from text descriptions.", "primary_task": "Music Generation", "categories": ["Music Generation", "Audio"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Genre, mood, lyric prompts", "outputs": "Generated music tracks"},
    {"name": "AIVA", "url": "https://www.aiva.ai", "company": "AIVA Technologies", "description": "AI music composition assistant that generates emotional soundtrack music for films, games, and commercial projects.", "primary_task": "Music Generation", "categories": ["Music Generation", "Soundtrack"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Style presets, mood, duration settings", "outputs": "Original music compositions"},

    # ── Coding / Development ──
    {"name": "GitHub Copilot", "url": "https://github.com/features/copilot", "company": "GitHub / Microsoft", "description": "AI pair programmer that provides real-time code suggestions, completions, and entire function implementations within IDEs.", "primary_task": "Code Generation", "categories": ["Coding", "Developer Tools"], "pricing": "PAID", "open_source": False, "inputs": "Code context, comments, function signatures", "outputs": "Code suggestions, completions, test cases"},
    {"name": "Cursor", "url": "https://www.cursor.com", "company": "Anysphere", "description": "AI-first code editor built for pair programming with AI, featuring intelligent code generation, editing, and debugging.", "primary_task": "Code Generation", "categories": ["Coding", "IDE"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Code context, natural language instructions", "outputs": "Generated code, code edits, explanations"},
    {"name": "Replit AI", "url": "https://replit.com/ai", "company": "Replit", "description": "AI-powered coding environment for building, deploying, and collaborating on software projects with AI assistance.", "primary_task": "Code Generation", "categories": ["Coding", "Cloud IDE"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Natural language prompts, code context", "outputs": "Generated applications, code, deployments"},
    {"name": "Tabnine", "url": "https://www.tabnine.com", "company": "Tabnine", "description": "AI code completion tool that provides whole-line and full-function code suggestions in multiple programming languages.", "primary_task": "Code Completion", "categories": ["Coding", "Developer Tools"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Code context, programming language", "outputs": "Code completions, function suggestions"},
    {"name": "Codeium", "url": "https://codeium.com", "company": "Exafunction", "description": "Free AI-powered code completion and search tool supporting 70+ programming languages with IDE integration.", "primary_task": "Code Completion", "categories": ["Coding", "Developer Tools"], "pricing": "FREE", "open_source": False, "inputs": "Code context, natural language queries", "outputs": "Code completions, search results"},
    {"name": "Sourcegraph Cody", "url": "https://sourcegraph.com/cody", "company": "Sourcegraph", "description": "AI coding assistant that understands your entire codebase to provide context-aware code generation and explanations.", "primary_task": "Code Generation", "categories": ["Coding", "Code Search"], "pricing": "FREEMIUM", "open_source": True, "inputs": "Codebase context, questions, prompts", "outputs": "Code generation, explanations, refactoring"},
    {"name": "Amazon CodeWhisperer", "url": "https://aws.amazon.com/codewhisperer", "company": "Amazon Web Services", "description": "AI coding companion by AWS that generates real-time code suggestions and identifies security vulnerabilities.", "primary_task": "Code Generation", "categories": ["Coding", "Security"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Code context, comments", "outputs": "Code suggestions, security scans"},
    {"name": "Devin", "url": "https://www.cognition.ai/devin", "company": "Cognition AI", "description": "Autonomous AI software engineer capable of planning, coding, debugging, and deploying entire software projects independently.", "primary_task": "Autonomous Coding", "categories": ["Coding", "AI Agent"], "pricing": "PAID", "open_source": False, "inputs": "Natural language task descriptions", "outputs": "Complete code implementations, pull requests"},

    # ── Search / Research ──
    {"name": "Perplexity", "url": "https://www.perplexity.ai", "company": "Perplexity AI", "description": "AI-powered search engine that provides direct answers with cited sources, combining web search with language model reasoning.", "primary_task": "AI Search", "categories": ["Search", "Research"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Natural language questions", "outputs": "Sourced answers with citations"},
    {"name": "You.com", "url": "https://you.com", "company": "You.com", "description": "AI search engine offering personalized search results with AI chat, image generation, and code generation capabilities.", "primary_task": "AI Search", "categories": ["Search", "Chatbot"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Search queries, natural language questions", "outputs": "AI-generated answers, search results, images"},
    {"name": "Consensus", "url": "https://consensus.app", "company": "Consensus", "description": "AI-powered academic search engine that uses language models to analyze and synthesize findings from peer-reviewed research papers.", "primary_task": "Research", "categories": ["Search", "Academic", "Research"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Research questions", "outputs": "Synthesized answers from scientific papers"},
    {"name": "Elicit", "url": "https://elicit.com", "company": "Elicit", "description": "AI research assistant that automates literature review by finding relevant papers, extracting key findings, and synthesizing results.", "primary_task": "Research", "categories": ["Research", "Academic"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Research questions, paper collections", "outputs": "Literature reviews, extracted data tables"},
    {"name": "Semantic Scholar", "url": "https://www.semanticscholar.org", "company": "Allen Institute for AI", "description": "AI-powered academic search engine providing intelligent search, paper recommendations, and citation analysis for scientific literature.", "primary_task": "Research", "categories": ["Search", "Academic"], "pricing": "FREE", "open_source": True, "inputs": "Search queries, paper titles, author names", "outputs": "Research papers, citation graphs, summaries"},

    # ── Productivity / Business ──
    {"name": "Otter.ai", "url": "https://otter.ai", "company": "Otter.ai", "description": "AI meeting assistant that provides real-time transcription, automated meeting notes, and action item extraction.", "primary_task": "Transcription", "categories": ["Productivity", "Transcription", "Meetings"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Audio/video meetings, recordings", "outputs": "Transcripts, meeting summaries, action items"},
    {"name": "Fireflies.ai", "url": "https://fireflies.ai", "company": "Fireflies.ai", "description": "AI meeting assistant that records, transcribes, and analyzes voice conversations across video conferencing platforms.", "primary_task": "Transcription", "categories": ["Productivity", "Meetings"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Meeting recordings, calls", "outputs": "Transcripts, summaries, searchable notes"},
    {"name": "Tome", "url": "https://tome.app", "company": "Tome", "description": "AI-powered presentation and storytelling tool that generates polished slide decks from text prompts and outlines.", "primary_task": "Presentation Generation", "categories": ["Presentations", "Productivity"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, document outlines", "outputs": "Generated presentations, slide decks"},
    {"name": "Beautiful.ai", "url": "https://www.beautiful.ai", "company": "Beautiful.ai", "description": "AI presentation software that automatically designs professional slides with smart formatting and layout suggestions.", "primary_task": "Presentation Generation", "categories": ["Presentations", "Design"], "pricing": "PAID", "open_source": False, "inputs": "Content text, data, images", "outputs": "Professionally designed presentations"},
    {"name": "Mem", "url": "https://mem.ai", "company": "Mem Labs", "description": "AI-powered note-taking and knowledge management tool that organizes information and surfaces relevant context automatically.", "primary_task": "Knowledge Management", "categories": ["Productivity", "Notes", "Knowledge Management"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Notes, documents, conversations", "outputs": "Organized knowledge base, contextual suggestions"},
    {"name": "Reclaim AI", "url": "https://reclaim.ai", "company": "Reclaim AI", "description": "AI-powered calendar management tool that automatically schedules tasks, habits, and meetings for optimal time management.", "primary_task": "Calendar Management", "categories": ["Productivity", "Scheduling"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Tasks, habits, meeting preferences", "outputs": "Optimized calendar schedules"},

    # ── Data / Analytics ──
    {"name": "Julius AI", "url": "https://julius.ai", "company": "Julius AI", "description": "AI data analysis tool that lets users analyze data, create visualizations, and generate insights using natural language.", "primary_task": "Data Analysis", "categories": ["Data Analysis", "Visualization"], "pricing": "FREEMIUM", "open_source": False, "inputs": "CSV files, spreadsheets, databases", "outputs": "Charts, analyses, data insights"},
    {"name": "Akkio", "url": "https://www.akkio.com", "company": "Akkio", "description": "No-code AI platform for building predictive models, data transformations, and automated analytics without programming.", "primary_task": "Predictive Analytics", "categories": ["Data Analysis", "Machine Learning", "No-Code"], "pricing": "PAID", "open_source": False, "inputs": "Tabular data, CSV files", "outputs": "Predictions, analytics dashboards, reports"},
    {"name": "Obviously AI", "url": "https://www.obviously.ai", "company": "Obviously AI", "description": "No-code machine learning platform for building, deploying, and sharing predictive models from tabular data.", "primary_task": "Predictive Analytics", "categories": ["Machine Learning", "No-Code"], "pricing": "PAID", "open_source": False, "inputs": "CSV data, prediction targets", "outputs": "ML models, predictions, reports"},

    # ── Automation / Agents / No-Code ──
    {"name": "Zapier AI", "url": "https://zapier.com/ai", "company": "Zapier", "description": "AI-powered automation platform connecting 6000+ apps with AI actions for chatbots, data extraction, and workflow automation.", "primary_task": "Workflow Automation", "categories": ["Automation", "No-Code", "Integration"], "pricing": "FREEMIUM", "open_source": False, "inputs": "App connections, trigger events, prompts", "outputs": "Automated workflows, chatbots, data transformations"},
    {"name": "Make (Integromat)", "url": "https://www.make.com", "company": "Make (Celonis)", "description": "Visual automation platform with AI capabilities for building complex integrations and automated workflows between apps.", "primary_task": "Workflow Automation", "categories": ["Automation", "No-Code", "Integration"], "pricing": "FREEMIUM", "open_source": False, "inputs": "App connections, data triggers", "outputs": "Automated multi-step workflows"},
    {"name": "AutoGPT", "url": "https://github.com/Significant-Gravitas/AutoGPT", "company": "Significant Gravitas", "description": "Open-source autonomous AI agent that chains LLM calls to accomplish complex tasks with minimal human intervention.", "primary_task": "AI Agent", "categories": ["AI Agent", "Automation", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Goal descriptions, task specifications", "outputs": "Completed tasks, generated artifacts"},
    {"name": "LangChain", "url": "https://github.com/langchain-ai/langchain", "company": "LangChain", "description": "Open-source framework for building applications powered by language models with chains, agents, and retrieval capabilities.", "primary_task": "LLM Framework", "categories": ["Developer Tools", "Framework", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "LLM configurations, data sources, prompts", "outputs": "LLM-powered applications, agent chains"},
    {"name": "CrewAI", "url": "https://github.com/crewAIInc/crewAI", "company": "CrewAI", "description": "Framework for orchestrating role-playing AI agents that collaborate to accomplish complex tasks autonomously.", "primary_task": "AI Agent", "categories": ["AI Agent", "Framework", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Agent role definitions, task descriptions", "outputs": "Collaborative agent outputs, completed tasks"},

    # ── Design / UI / Creative ──
    {"name": "Figma AI", "url": "https://www.figma.com/ai", "company": "Figma", "description": "AI features integrated into Figma for generating UI designs, renaming layers, summarizing designs, and visual search.", "primary_task": "UI Design", "categories": ["Design", "UI/UX"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Design context, text prompts", "outputs": "Generated UI components, design suggestions"},
    {"name": "Galileo AI", "url": "https://www.usegalileo.ai", "company": "Galileo AI", "description": "AI-powered UI design tool that generates editable UI designs from text descriptions for web and mobile apps.", "primary_task": "UI Design", "categories": ["Design", "UI/UX"], "pricing": "PAID", "open_source": False, "inputs": "Text descriptions of desired UI", "outputs": "Editable UI designs, Figma exports"},
    {"name": "Photoroom", "url": "https://www.photoroom.com", "company": "Photoroom", "description": "AI photo editing tool specializing in background removal, product photography enhancement, and image composition.", "primary_task": "Photo Editing", "categories": ["Photo Editing", "E-commerce"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Photos, product images", "outputs": "Edited images, background-removed photos"},
    {"name": "Remove.bg", "url": "https://www.remove.bg", "company": "Kaleido AI", "description": "AI-powered tool for automatically removing backgrounds from images with high accuracy in seconds.", "primary_task": "Background Removal", "categories": ["Photo Editing", "Image Processing"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Images with backgrounds", "outputs": "Images with transparent backgrounds"},
    {"name": "Luma AI", "url": "https://lumalabs.ai", "company": "Luma AI", "description": "AI platform for 3D capture and reconstruction, creating photorealistic 3D models from photos and videos.", "primary_task": "3D Generation", "categories": ["3D Modeling", "Computer Vision"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Photos, videos of objects/scenes", "outputs": "3D models, NeRF reconstructions"},

    # ── Translation / Language ──
    {"name": "DeepL", "url": "https://www.deepl.com", "company": "DeepL SE", "description": "Neural machine translation service providing highly accurate translations for 30+ languages with document translation support.", "primary_task": "Translation", "categories": ["Translation", "Language"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text, documents in source language", "outputs": "Translated text maintaining formatting"},

    # ── Customer Service / Sales ──
    {"name": "Intercom Fin", "url": "https://www.intercom.com/fin", "company": "Intercom", "description": "AI customer service agent that resolves support queries using company knowledge base with human handoff capabilities.", "primary_task": "Customer Service", "categories": ["Customer Service", "Chatbot"], "pricing": "PAID", "open_source": False, "inputs": "Customer questions, knowledge base", "outputs": "Automated support responses, ticket routing"},
    {"name": "Zendesk AI", "url": "https://www.zendesk.com/ai", "company": "Zendesk", "description": "AI-powered customer service platform with intelligent triage, agent assist, and automated response capabilities.", "primary_task": "Customer Service", "categories": ["Customer Service", "Helpdesk"], "pricing": "PAID", "open_source": False, "inputs": "Support tickets, customer queries", "outputs": "Automated responses, ticket classifications"},
    {"name": "Drift", "url": "https://www.salesloft.com/drift", "company": "Salesloft", "description": "Conversational AI platform for B2B sales and marketing with intelligent chatbots and buyer engagement automation.", "primary_task": "Conversational Marketing", "categories": ["Sales", "Marketing", "Chatbot"], "pricing": "PAID", "open_source": False, "inputs": "Website visitors, lead information", "outputs": "Qualified leads, meeting bookings, chat conversations"},

    # ── SEO / Marketing ──
    {"name": "Surfer SEO", "url": "https://surferseo.com", "company": "Surfer", "description": "AI-powered SEO optimization tool for creating search-engine-optimized content with real-time scoring and keyword analysis.", "primary_task": "SEO Optimization", "categories": ["SEO", "Content Marketing"], "pricing": "PAID", "open_source": False, "inputs": "Target keywords, content drafts", "outputs": "SEO scores, optimization suggestions, content briefs"},
    {"name": "Clearscope", "url": "https://www.clearscope.io", "company": "Clearscope", "description": "AI content optimization platform that uses NLP to help writers create comprehensive, SEO-friendly content.", "primary_task": "SEO Optimization", "categories": ["SEO", "Content Marketing"], "pricing": "PAID", "open_source": False, "inputs": "Target keywords, content drafts", "outputs": "Content grades, keyword recommendations"},
    {"name": "MarketMuse", "url": "https://www.marketmuse.com", "company": "MarketMuse", "description": "AI content intelligence platform for content planning, optimization, and competitive analysis using topic modeling.", "primary_task": "Content Strategy", "categories": ["SEO", "Content Strategy"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Website URLs, target topics", "outputs": "Content plans, briefs, competitive analysis"},

    # ── Education / Learning ──
    {"name": "Khanmigo", "url": "https://www.khanacademy.org/khan-labs", "company": "Khan Academy", "description": "AI tutoring assistant by Khan Academy providing personalized learning guidance, homework help, and Socratic teaching across subjects.", "primary_task": "AI Tutoring", "categories": ["Education", "Tutoring"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Student questions, learning topics", "outputs": "Guided explanations, practice problems"},
    {"name": "Duolingo Max", "url": "https://www.duolingo.com/max", "company": "Duolingo", "description": "AI-powered language learning features including roleplay conversations and intelligent explanations of mistakes.", "primary_task": "Language Learning", "categories": ["Education", "Language Learning"], "pricing": "PAID", "open_source": False, "inputs": "Language exercises, conversation prompts", "outputs": "Feedback, explanations, roleplay dialogues"},
    {"name": "Socratic by Google", "url": "https://socratic.org", "company": "Google", "description": "AI-powered homework help app that uses Google AI to provide visual explanations and step-by-step solutions for academic subjects.", "primary_task": "Education", "categories": ["Education", "Homework Help"], "pricing": "FREE", "open_source": False, "inputs": "Photos of homework problems, text questions", "outputs": "Step-by-step explanations, visual guides"},

    # ── Security / Legal / Compliance ──
    {"name": "Snyk AI", "url": "https://snyk.io", "company": "Snyk", "description": "AI-powered developer security platform for finding and fixing vulnerabilities in code, dependencies, containers, and infrastructure.", "primary_task": "Security Analysis", "categories": ["Security", "Developer Tools"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Source code, container images, IaC configs", "outputs": "Vulnerability reports, fix suggestions"},
    {"name": "Harvey AI", "url": "https://www.harvey.ai", "company": "Harvey AI", "description": "AI assistant for legal professionals that assists with legal research, contract analysis, document drafting, and due diligence.", "primary_task": "Legal AI", "categories": ["Legal", "Document Analysis"], "pricing": "PAID", "open_source": False, "inputs": "Legal documents, research queries, contracts", "outputs": "Legal analyses, draft documents, research summaries"},

    # ── Healthcare / Science ──
    {"name": "AlphaFold", "url": "https://alphafold.ebi.ac.uk", "company": "Google DeepMind", "description": "AI system that predicts 3D protein structures from amino acid sequences with near-experimental accuracy.", "primary_task": "Protein Prediction", "categories": ["Science", "Biology", "Drug Discovery"], "pricing": "FREE", "open_source": True, "inputs": "Amino acid sequences", "outputs": "Predicted 3D protein structures"},

    # ── Chatbot Builders / Platforms ──
    {"name": "Botpress", "url": "https://botpress.com", "company": "Botpress", "description": "Open-source chatbot building platform with visual flow editor, NLU engine, and multi-channel deployment.", "primary_task": "Chatbot Building", "categories": ["Chatbot", "Developer Tools", "Open Source"], "pricing": "FREEMIUM", "open_source": True, "inputs": "Conversation flows, knowledge bases, intents", "outputs": "Deployed chatbots across channels"},
    {"name": "Voiceflow", "url": "https://www.voiceflow.com", "company": "Voiceflow", "description": "Collaborative AI agent building platform for designing, prototyping, and launching conversational AI experiences.", "primary_task": "Chatbot Building", "categories": ["Chatbot", "Voice AI", "No-Code"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Conversation designs, knowledge bases", "outputs": "Deployed AI agents and chatbots"},

    # ── Spreadsheets / Documents ──
    {"name": "SheetAI", "url": "https://www.sheetai.app", "company": "SheetAI", "description": "Google Sheets add-on that uses AI to generate text, extract data, and clean spreadsheets with custom AI functions.", "primary_task": "Spreadsheet AI", "categories": ["Productivity", "Spreadsheets"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Spreadsheet data, AI function prompts", "outputs": "Generated data, cleaned spreadsheets"},
    {"name": "Rows AI", "url": "https://rows.com", "company": "Rows", "description": "AI-powered spreadsheet tool that combines data analysis with AI-generated summaries, classifications, and data enrichment.", "primary_task": "Spreadsheet AI", "categories": ["Productivity", "Data Analysis"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Spreadsheet data, natural language queries", "outputs": "AI-analyzed data, summaries, charts"},

    # ── AI Infrastructure / MLOps ──
    {"name": "Weights & Biases", "url": "https://wandb.ai", "company": "Weights & Biases", "description": "MLOps platform for experiment tracking, model versioning, dataset management, and collaborative machine learning workflows.", "primary_task": "ML Experiment Tracking", "categories": ["MLOps", "Developer Tools"], "pricing": "FREEMIUM", "open_source": False, "inputs": "ML training metrics, model artifacts, datasets", "outputs": "Experiment dashboards, model registries, reports"},
    {"name": "Hugging Face", "url": "https://huggingface.co", "company": "Hugging Face", "description": "Open-source AI community platform hosting models, datasets, and Spaces for building, training, and deploying ML applications.", "primary_task": "Model Hub", "categories": ["MLOps", "Open Source", "Model Hosting"], "pricing": "FREEMIUM", "open_source": True, "inputs": "Models, datasets, code", "outputs": "Hosted models, inference APIs, Spaces apps"},
    {"name": "Replicate", "url": "https://replicate.com", "company": "Replicate", "description": "Cloud platform for running open-source machine learning models with a simple API, supporting image, video, and text generation.", "primary_task": "Model Hosting", "categories": ["MLOps", "Cloud API"], "pricing": "PAID", "open_source": False, "inputs": "Model selections, input parameters", "outputs": "Model inference results via API"},
    {"name": "Modal", "url": "https://modal.com", "company": "Modal Labs", "description": "Cloud platform for running generative AI, large-scale batch jobs, and GPU-intensive workloads with serverless infrastructure.", "primary_task": "Cloud Computing", "categories": ["Cloud", "MLOps", "Infrastructure"], "pricing": "PAID", "open_source": False, "inputs": "Python functions, container configs", "outputs": "Serverless compute results, deployed endpoints"},
    {"name": "Together AI", "url": "https://www.together.ai", "company": "Together AI", "description": "Cloud platform for running, training, and fine-tuning open-source AI models with fast inference and competitive pricing.", "primary_task": "Model Inference", "categories": ["Cloud API", "Model Hosting"], "pricing": "PAID", "open_source": False, "inputs": "API requests, model selections", "outputs": "Model inference results, fine-tuned models"},

    # ── RAG / Knowledge / Embeddings ──
    {"name": "Pinecone", "url": "https://www.pinecone.io", "company": "Pinecone", "description": "Managed vector database for building high-performance similarity search and retrieval-augmented generation (RAG) applications.", "primary_task": "Vector Database", "categories": ["Database", "RAG", "Search"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Vector embeddings, metadata, queries", "outputs": "Similarity search results, nearest neighbors"},
    {"name": "Weaviate", "url": "https://weaviate.io", "company": "Weaviate", "description": "Open-source vector database for AI applications with built-in vectorization, hybrid search, and generative modules.", "primary_task": "Vector Database", "categories": ["Database", "Open Source", "RAG"], "pricing": "FREEMIUM", "open_source": True, "inputs": "Data objects, vector queries", "outputs": "Semantic search results, RAG outputs"},
    {"name": "ChromaDB", "url": "https://www.trychroma.com", "company": "Chroma", "description": "Open-source embedding database for building AI applications with LLMs, supporting document storage and semantic retrieval.", "primary_task": "Vector Database", "categories": ["Database", "Open Source", "RAG"], "pricing": "FREE", "open_source": True, "inputs": "Documents, embeddings, queries", "outputs": "Relevant document retrieval results"},
    {"name": "LlamaIndex", "url": "https://www.llamaindex.ai", "company": "LlamaIndex", "description": "Data framework for connecting custom data sources to large language models for retrieval-augmented generation and agents.", "primary_task": "RAG Framework", "categories": ["Framework", "RAG", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Documents, APIs, databases", "outputs": "RAG pipelines, query engines, agent tools"},

    # ── Transcription / Speech-to-Text ──
    {"name": "Whisper", "url": "https://github.com/openai/whisper", "company": "OpenAI", "description": "Open-source automatic speech recognition model that transcribes and translates audio in multiple languages with high accuracy.", "primary_task": "Speech-to-Text", "categories": ["Transcription", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Audio files in various formats", "outputs": "Text transcripts, translations"},
    {"name": "AssemblyAI", "url": "https://www.assemblyai.com", "company": "AssemblyAI", "description": "AI speech-to-text API with speaker diarization, sentiment analysis, content moderation, and topic detection capabilities.", "primary_task": "Speech-to-Text", "categories": ["Transcription", "API"], "pricing": "PAID", "open_source": False, "inputs": "Audio/video files, streaming audio", "outputs": "Transcripts, speaker labels, sentiment analysis"},

    # ── Email / Communication ──
    {"name": "Superhuman AI", "url": "https://superhuman.com", "company": "Superhuman", "description": "AI-powered email client with instant reply drafting, email summarization, and intelligent inbox management features.", "primary_task": "Email AI", "categories": ["Email", "Productivity"], "pricing": "PAID", "open_source": False, "inputs": "Email threads, inbox data", "outputs": "Draft replies, email summaries, prioritized inbox"},
    {"name": "Lavender", "url": "https://www.lavender.ai", "company": "Lavender", "description": "AI email coaching tool for sales teams that analyzes and scores emails to improve reply rates and engagement.", "primary_task": "Sales Email", "categories": ["Sales", "Email"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Email drafts, recipient data", "outputs": "Email scores, improvement suggestions"},

    # ── More tools ──
    {"name": "Anthropic API", "url": "https://docs.anthropic.com", "company": "Anthropic", "description": "API platform providing access to Claude models for text generation, analysis, coding, and vision tasks.", "primary_task": "API Platform", "categories": ["API", "LLM Platform"], "pricing": "PAID", "open_source": False, "inputs": "API requests with prompts", "outputs": "Generated text, analysis, code"},
    {"name": "OpenAI API", "url": "https://platform.openai.com", "company": "OpenAI", "description": "Developer platform providing API access to GPT, DALL-E, Whisper, and embedding models for building AI applications.", "primary_task": "API Platform", "categories": ["API", "LLM Platform"], "pricing": "PAID", "open_source": False, "inputs": "API requests with prompts/data", "outputs": "Text, images, embeddings, transcriptions"},
    {"name": "Groq", "url": "https://groq.com", "company": "Groq", "description": "AI inference platform using custom LPU hardware to deliver ultra-fast inference speeds for large language models.", "primary_task": "AI Inference", "categories": ["Infrastructure", "API"], "pricing": "FREEMIUM", "open_source": False, "inputs": "API requests, model selections", "outputs": "Ultra-fast model inference results"},
    {"name": "Ollama", "url": "https://ollama.com", "company": "Ollama", "description": "Tool for running large language models locally on personal computers with simple setup and model management.", "primary_task": "Local LLM", "categories": ["Developer Tools", "Open Source", "Local AI"], "pricing": "FREE", "open_source": True, "inputs": "Model selections, text prompts", "outputs": "Locally generated text responses"},
    {"name": "LM Studio", "url": "https://lmstudio.ai", "company": "LM Studio", "description": "Desktop application for discovering, downloading, and running local LLMs with a chat interface and local API server.", "primary_task": "Local LLM", "categories": ["Developer Tools", "Local AI"], "pricing": "FREE", "open_source": False, "inputs": "Model downloads, text prompts", "outputs": "Locally generated text, local API endpoints"},
    {"name": "Jan", "url": "https://jan.ai", "company": "Jan", "description": "Open-source desktop application for running AI models locally with privacy, supporting multiple model formats.", "primary_task": "Local LLM", "categories": ["Local AI", "Open Source", "Privacy"], "pricing": "FREE", "open_source": True, "inputs": "Local model files, prompts", "outputs": "Private local AI responses"},
    {"name": "Cohere", "url": "https://cohere.com", "company": "Cohere", "description": "Enterprise AI platform providing language models for text generation, embeddings, classification, and RAG for business applications.", "primary_task": "Enterprise LLM", "categories": ["API", "Enterprise AI"], "pricing": "PAID", "open_source": False, "inputs": "Text data, business documents", "outputs": "Text generation, embeddings, classifications"},
    {"name": "AI21 Labs", "url": "https://www.ai21.com", "company": "AI21 Labs", "description": "AI platform offering Jamba models and enterprise AI solutions for text generation, summarization, and paraphrasing.", "primary_task": "Enterprise LLM", "categories": ["API", "Enterprise AI"], "pricing": "PAID", "open_source": False, "inputs": "Text, documents, API requests", "outputs": "Generated text, summaries, paraphrased content"},
    {"name": "Mistral AI", "url": "https://mistral.ai", "company": "Mistral AI", "description": "Open-weight AI model provider offering efficient, high-performance language models for commercial and research applications.", "primary_task": "LLM Provider", "categories": ["API", "Open Source", "LLM Platform"], "pricing": "FREEMIUM", "open_source": True, "inputs": "API requests, text prompts", "outputs": "Text generation, code, embeddings"},
    {"name": "Undetectable AI", "url": "https://undetectable.ai", "company": "Undetectable AI", "description": "AI text humanization tool that rewrites AI-generated content to bypass AI detection tools while maintaining meaning.", "primary_task": "AI Text Humanization", "categories": ["Writing", "Content"], "pricing": "PAID", "open_source": False, "inputs": "AI-generated text", "outputs": "Humanized text that bypasses detectors"},
    {"name": "Gamma", "url": "https://gamma.app", "company": "Gamma", "description": "AI-powered tool for creating presentations, documents, and webpages from prompts with automatic formatting and design.", "primary_task": "Presentation Generation", "categories": ["Presentations", "Documents"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, outlines, notes", "outputs": "Formatted presentations, documents, webpages"},
    {"name": "v0", "url": "https://v0.dev", "company": "Vercel", "description": "AI-powered UI generation tool by Vercel that creates React components and web interfaces from text descriptions.", "primary_task": "UI Generation", "categories": ["Web Development", "Code Generation"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text descriptions of desired UI", "outputs": "React components, shadcn/ui code"},
    {"name": "Bolt.new", "url": "https://bolt.new", "company": "StackBlitz", "description": "AI-powered full-stack web development tool that generates, runs, and deploys complete web applications in the browser.", "primary_task": "Web Development", "categories": ["Web Development", "Code Generation"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Natural language app descriptions", "outputs": "Complete web applications, deployments"},
    {"name": "Lovable", "url": "https://lovable.dev", "company": "Lovable", "description": "AI-powered full-stack application builder that creates production-ready web apps from natural language descriptions.", "primary_task": "App Building", "categories": ["Web Development", "No-Code"], "pricing": "FREEMIUM", "open_source": False, "inputs": "App descriptions, feature requests", "outputs": "Deployed web applications"},
    {"name": "Cline", "url": "https://github.com/cline/cline", "company": "Cline", "description": "Autonomous AI coding agent for VS Code that can create and edit files, execute commands, and use the browser.", "primary_task": "Code Generation", "categories": ["Coding", "AI Agent", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Natural language instructions, codebase context", "outputs": "Code changes, terminal commands, file edits"},
    {"name": "Aider", "url": "https://aider.chat", "company": "Aider", "description": "AI pair programming tool in the terminal that edits code in local git repos using GPT and Claude models.", "primary_task": "Code Generation", "categories": ["Coding", "Terminal", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Natural language instructions, git repo context", "outputs": "Code edits committed to git"},
    {"name": "Windsurf", "url": "https://codeium.com/windsurf", "company": "Codeium", "description": "AI-powered code editor with agentic capabilities for autonomous multi-file editing and deep codebase understanding.", "primary_task": "Code Generation", "categories": ["IDE", "Coding"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Natural language instructions, code context", "outputs": "Multi-file code changes, explanations"},
    {"name": "Vercel AI SDK", "url": "https://sdk.vercel.ai", "company": "Vercel", "description": "TypeScript toolkit for building AI-powered applications with streaming support for multiple LLM providers.", "primary_task": "AI Development Kit", "categories": ["Developer Tools", "Framework"], "pricing": "FREE", "open_source": True, "inputs": "LLM provider configs, prompts", "outputs": "Streaming AI responses, UI components"},
    {"name": "Langfuse", "url": "https://langfuse.com", "company": "Langfuse", "description": "Open-source LLM engineering platform for tracing, evaluating, and monitoring production LLM applications.", "primary_task": "LLM Observability", "categories": ["MLOps", "Developer Tools", "Open Source"], "pricing": "FREEMIUM", "open_source": True, "inputs": "LLM traces, evaluation data", "outputs": "Dashboards, cost analytics, quality metrics"},
    {"name": "Helicone", "url": "https://www.helicone.ai", "company": "Helicone", "description": "Open-source LLM observability platform for logging, monitoring, and optimizing AI application performance and costs.", "primary_task": "LLM Observability", "categories": ["MLOps", "Developer Tools"], "pricing": "FREEMIUM", "open_source": True, "inputs": "LLM API requests via proxy", "outputs": "Usage analytics, cost tracking, latency metrics"},
    {"name": "Roboflow", "url": "https://roboflow.com", "company": "Roboflow", "description": "Computer vision platform for building, deploying, and managing visual AI models with dataset management and auto-labeling.", "primary_task": "Computer Vision", "categories": ["Computer Vision", "MLOps"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Images, videos, annotations", "outputs": "Trained vision models, inference APIs"},
    {"name": "Hume AI", "url": "https://www.hume.ai", "company": "Hume AI", "description": "Empathic AI platform providing emotion recognition and measurement from voice, face, and language for human-AI interaction.", "primary_task": "Emotion AI", "categories": ["Voice AI", "Emotion Recognition"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Voice recordings, video, text", "outputs": "Emotion predictions, expressive TTS"},
    {"name": "Character.ai", "url": "https://character.ai", "company": "Character Technologies", "description": "Platform for creating and chatting with AI characters, each with unique personalities, knowledge, and conversational styles.", "primary_task": "AI Characters", "categories": ["Entertainment", "Chatbot"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Character definitions, conversation prompts", "outputs": "AI character conversations"},
    {"name": "Civitai", "url": "https://civitai.com", "company": "Civitai", "description": "Community platform for sharing, discovering, and downloading AI-generated art models, LoRAs, and checkpoints for Stable Diffusion.", "primary_task": "Model Sharing", "categories": ["Community", "Image Generation", "Open Source"], "pricing": "FREEMIUM", "open_source": True, "inputs": "Model uploads, search queries", "outputs": "AI model downloads, community galleries"},
    {"name": "Stability AI API", "url": "https://platform.stability.ai", "company": "Stability AI", "description": "API platform providing access to Stable Diffusion models for image generation, editing, upscaling, and video generation.", "primary_task": "Image Generation API", "categories": ["API", "Image Generation"], "pricing": "PAID", "open_source": False, "inputs": "API requests with prompts/images", "outputs": "Generated images, upscaled images, videos"},
    {"name": "Typeface", "url": "https://www.typeface.ai", "company": "Typeface", "description": "Enterprise generative AI platform for creating brand-consistent content across marketing channels at scale.", "primary_task": "Enterprise Content", "categories": ["Enterprise AI", "Content Generation", "Marketing"], "pricing": "PAID", "open_source": False, "inputs": "Brand guidelines, content briefs", "outputs": "Brand-consistent marketing content"},
    {"name": "Scribe", "url": "https://scribehow.com", "company": "Scribe", "description": "AI-powered documentation tool that automatically creates step-by-step guides and SOPs by recording user workflows.", "primary_task": "Documentation", "categories": ["Productivity", "Documentation"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Screen recordings, workflow captures", "outputs": "Step-by-step guides, process documentation"},
    {"name": "Liner", "url": "https://getliner.com", "company": "Liner", "description": "AI search and research assistant that highlights web content, summarizes articles, and provides AI-powered answers.", "primary_task": "Research", "categories": ["Search", "Productivity", "Research"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Web pages, research queries", "outputs": "Highlights, summaries, AI answers"},
    {"name": "Speechify", "url": "https://speechify.com", "company": "Speechify", "description": "AI text-to-speech platform that converts documents, articles, and web pages into natural-sounding audio for listening on the go.", "primary_task": "Text-to-Speech", "categories": ["Text-to-Speech", "Accessibility"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text documents, PDFs, web pages", "outputs": "Natural-sounding audio narration"},
    {"name": "Kling AI", "url": "https://klingai.com", "company": "Kuaishou", "description": "AI video generation platform creating high-quality videos from text and image prompts with advanced motion generation.", "primary_task": "Video Generation", "categories": ["Video Generation"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text prompts, reference images", "outputs": "Generated video clips"},
    {"name": "Sora", "url": "https://openai.com/sora", "company": "OpenAI", "description": "Text-to-video AI model by OpenAI capable of generating realistic and imaginative video scenes from text instructions.", "primary_task": "Video Generation", "categories": ["Video Generation"], "pricing": "PAID", "open_source": False, "inputs": "Text prompts describing video scenes", "outputs": "Generated video clips up to 1 minute"},
    {"name": "Flux", "url": "https://blackforestlabs.ai", "company": "Black Forest Labs", "description": "State-of-the-art open-source text-to-image model family offering high-quality image generation with strong prompt adherence.", "primary_task": "Image Generation", "categories": ["Image Generation", "Open Source"], "pricing": "FREEMIUM", "open_source": True, "inputs": "Text prompts", "outputs": "High-quality generated images"},
    {"name": "NotebookLM", "url": "https://notebooklm.google.com", "company": "Google", "description": "AI research assistant by Google that generates summaries, answers questions, and creates audio overviews from uploaded documents.", "primary_task": "Research", "categories": ["Research", "Knowledge Management"], "pricing": "FREE", "open_source": False, "inputs": "Documents, PDFs, web links", "outputs": "Summaries, Q&A responses, audio overviews"},
    {"name": "Napkin AI", "url": "https://www.napkin.ai", "company": "Napkin AI", "description": "AI tool that transforms text into visual diagrams, infographics, and illustrations for presentations and content.", "primary_task": "Visual Content", "categories": ["Design", "Visualization"], "pricing": "FREEMIUM", "open_source": False, "inputs": "Text content, articles", "outputs": "Auto-generated diagrams and visuals"},
    {"name": "Perplexity Spaces", "url": "https://www.perplexity.ai/spaces", "company": "Perplexity AI", "description": "Collaborative AI research spaces for teams to organize searches, share findings, and build knowledge bases together.", "primary_task": "Research Collaboration", "categories": ["Research", "Collaboration"], "pricing": "PAID", "open_source": False, "inputs": "Research queries, shared files", "outputs": "Organized research collections, shared insights"},
    {"name": "Tldraw AI", "url": "https://www.tldraw.com", "company": "tldraw", "description": "AI-powered infinite canvas whiteboard that converts sketches and wireframes into functional UI code and designs.", "primary_task": "Wireframing", "categories": ["Design", "Prototyping", "Open Source"], "pricing": "FREE", "open_source": True, "inputs": "Freehand sketches, wireframes", "outputs": "Generated UI code, design exports"},
    {"name": "Veo 2", "url": "https://deepmind.google/technologies/veo", "company": "Google DeepMind", "description": "Advanced AI video generation model by Google DeepMind capable of creating high-fidelity, cinematic video from text prompts.", "primary_task": "Video Generation", "categories": ["Video Generation"], "pricing": "PAID", "open_source": False, "inputs": "Text and image prompts", "outputs": "High-fidelity generated videos"},
]


class ToolsAdapter(BaseAdapter):
    """
    Production-grade AI Tools discovery adapter.
    Uses curated seed data + GitHub API for open-source tool discovery.
    Does NOT fabricate records. Every record is traceable.
    """

    async def discover(self) -> List[Dict[str, str]]:
        """Return curated seed list — no scraping needed for known tools."""
        return CURATED_AI_TOOLS

    async def fetch_and_process(self) -> List[FullRecord]:
        """
        For curated tools, we already have verified metadata.
        LLM is NOT needed for description generation since we provide factual descriptions.
        This avoids wasting API quota on data we already have.
        """
        items = await self.discover()
        records = []

        for item in items:
            resolved_id, status = self.resolver.resolve(EntityType.TOOL, item["name"], item["url"])
            if status in ["EXACT_URL", "EXACT_NAME", "ALIAS"]:
                logger.info(f"Skipping duplicate tool: {item['name']}")
                continue

            # Map pricing string to enum
            pricing_map = {
                "FREE": "FREE", "FREEMIUM": "FREEMIUM",
                "PAID": "PAID", "ENTERPRISE": "ENTERPRISE"
            }
            pricing_val = pricing_map.get(item.get("pricing", "UNKNOWN"), "UNKNOWN")

            content = ToolContent(
                name=item["name"],
                company_or_developer=item.get("company"),
                description=item["description"],
                primary_task=item.get("primary_task"),
                categories=item.get("categories", []),
                pricing_model=pricing_val,
                is_open_source=item.get("open_source", False),
                launch_date=None,
                status="Active",
                official_website=item["url"],
                inputs=item.get("inputs"),
                outputs=item.get("outputs"),
                supported_platforms=None,
                has_api=None,
                logo_url=None,
                last_verified=datetime.datetime.utcnow().strftime("%Y-%m-%d")
            )

            record = FullRecord(
                id=resolved_id,
                recordType=EntityType.TOOL,
                source=SourceProvenance(name="Curated Seed List", url=item["url"]),
                content=content,
                collectedAt=datetime.datetime.utcnow().isoformat()
            )
            records.append(record)

        logger.info(f"Curated discovery produced {len(records)} tool records")
        return records
